---
# Install Chocolatey
- name: "Chocolatey"
  hosts: all
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
          state: present

# Install 7-Zip and Chrome with Chocolatey
- name: Ensure 7-Zip is installed via Chocolatey
  win_chocolatey:
    name: 7zip
    state: present

- name: Install Chrome
  win_chocolatey:
    name: chrome
    state: present

# Upgrade all Chocolatey packages
- name: Upgrade installed packages
  win_chocolatey:
    name: all
    state: latest