---
# Install Chocolatey
- name: Chocolatey
  hosts: all
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
          state: present

    # Install Packages
    - name: Install multiple packages sequentially
      win_chocolatey:
        name: '{{ item }}'
        state: present
      loop:
      - chrome
      - putty
      - windirstat

    # Upgrade all Chocolatey packages
    - name: Upgrade installed packages
      win_chocolatey:
        name: all
        state: latest