---
- hosts: all
    vars:
      rpm_agent_installer_url: https://download1491.mediafire.com/1ttf9w7n75fg/9zb9gtth9ri0nz8/SentinelAgent_linux_v21_5_3_2.rpm
      deb_agent_installer_url: https://your_url/SentinelAgent_Linux_version.deb
      registration_token: "eyJ1cmwiOiAiaHR0cHM6Ly91c2VhMS1wdXJwbGUuc2VudGluZWxvbmUubmV0IiwgInNpdGVfa2V5IjogImQ3ZjcwOGJjODZlNGQxMDcifQ=="

    tasks:

    -   name: Check that the sentinelctl exists
        stat:
          path: /opt/sentinelone/bin/sentinelctl
        become: true
        register: sentinelctl_exists

    -   name: Create temporary folder to place the installer
        file:
          path: /tmp/sentinel_installer
          state: directory
          mode: '0755'
        when: sentinelctl_exists.stat.exists == False

    -   name: Get SentinelAgent DEB package from remote location
        get_url:
          url: "{{ deb_agent_installer_url }}"
          dest: "/tmp/sentinel_installer/sentinelone_installer.deb"
          mode: '0777'
        when: sentinelctl_exists.stat.exists == False and ansible_facts['os_family'] == "Debian"

    -   name: Get SentinelAgent RPM package from remote location
        get_url:
          url: "{{ rpm_agent_installer_url }}"
          dest: "/tmp/sentinel_installer/sentinelone_installer.rpm"
          mode: '0777'
        when: sentinelctl_exists.stat.exists == False and ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version']|int >= 6.4

    -   name: Install the Linux Agent on Debian based distro
        command: dpkg -i /tmp/sentinel_installer/sentinelone_installer.deb
        become: true
        when: sentinelctl_exists.stat.exists == False and ansible_facts['os_family'] == "Debian"

    -   name: Install the Linux Agent on Red Hat based distro
        command: rpm -i --nodigest /tmp/sentinel_installer/sentinelone_installer.rpm
        become: true
        become_user: root
        become_method: sudo
        when: sentinelctl_exists.stat.exists == False and ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version']|int >= 6.4

    -   name: Apply the registration token to the agent
        command: /opt/sentinelone/bin/sentinelctl management token set {{ registration_token }}
        become_user: root
        become_method: sudo
        become: true
        when: sentinelctl_exists.stat.exists == False

    -   name: Start the SentinelOne agent
        command: /opt/sentinelone/bin/sentinelctl control start
        become_user: root
        become_method: sudo
        become: true

    -   name: Delete the installer folder
        file:
          path: /tmp/sentinel_installer
          state: absent
        become_user: root
        become_method: sudo
        become: true