---
- hosts: all
  tasks: 

  - name: Download S1 Agent
    win_shell: 'Invoke-WebRequest -Uri "https://download948.mediafire.com/sw18w3nfussg/p2cuxvmijlf3jl9/SentinelInstaller-x64_windows_64bit_v5_0_1_136.exe" -Outfile (New-Item -Path "C:\Temp\S1.exe" -Force)'

  - name: Execute a Powershell script
    win_shell: & C:\Temp\S1.exe /SITE_TOKEN=eyJ1cmwiOiAiaHR0cHM6Ly91c2VhMS1wdXJwbGUuc2VudGluZWxvbmUubmV0IiwgInNpdGVfa2V5IjogImQ3ZjcwOGJjODZlNGQxMDcifQ== /SILENT


    